### ISSUE TITLE
Patterns for Persistence

### ISSUE THREAD

**Issue by justinj** [hydro-project/hydroflow#103]
A common pattern in Dedalus programs is to persist some relation into the future via an inductive rule:
```datalog
q(X)@next :- q(X).
```

Translated naively to Hydroflow today, this would result in draining a buffer only to re-fill it the same way on the next iteration. We probably want some mechanism to allow us to designate a relation as "persisted" and thus not drained at the end of a tick.

This issue is to acknowledge two needs I see:
1. A way in Hydroflow to easily denote which buffers should be drained at the end of a tick and which should not, to avoid this churn, and
2. a representation in whatever higher-level IR we eventually adopt that can recognize patterns like `q(X)@next :- q(X).` and translate them into a form that can be handled more efficiently.

cc @MingweiSamuel @jhellerstein

**Comment by davidchuyaya** [comment]
Common patterns for persistence, aside from "just keep everything for the next timestep":

In [this](https://github.com/davidchuyaya/bud-paxos/blob/9982ecadfbc665e2e7629be37ae5a82b317a60b6/dedalus-paxos/proposer.txt#L87) example, `ballot` stores the proposer's current ballot (a single number). The ballot for the next timestep should either be the current ballot of the proposer (creation at t+1), or if a new ballot is chosen, the new ballot (conditional persist).
This is set to the next timestep instead of the current one so rules that check for incoming messages that match the current ballot don't execute over the newly generated ballot.

In [this](https://github.com/davidchuyaya/bud-paxos/blob/9982ecadfbc665e2e7629be37ae5a82b317a60b6/dedalus-paxos/proposer.txt#L103) example, p2a messages are not allowed to be sent until a timestep after a quorum of p1b messages have arrived. This is so p2a messages aren't assigned conflicting slot numbers for messages that we receive in p1b and have to resend (to commit). This can probably be addressed with some layers of aggregations instead, and can certainly be addressed in hydroflow with a few new strata.

In [this](https://github.com/davidchuyaya/bud-paxos/blob/9982ecadfbc665e2e7629be37ae5a82b317a60b6/dedalus-paxos/proposer.txt#L116) example, messages are resent to commit after receiving a quorum of p1b, but only messages which have not been sent before or committed (and would be in `proposedLog`). This requires negating `proposedLog`. Then, the messages that are resent are added to `proposedLog`. So adding back to `proposedLog` requires another timestep.

In [this](https://github.com/davidchuyaya/bud-paxos/blob/9982ecadfbc665e2e7629be37ae5a82b317a60b6/dedalus-paxos/proposer.txt#L119), the `proposedLog` of sent/committed messages is only persisted if the proposer is the leader. This is another "filter" for persistence.

In [this](https://github.com/davidchuyaya/bud-paxos/blob/9982ecadfbc665e2e7629be37ae5a82b317a60b6/dedalus-paxos/proposer.txt#L129), a new payload is added to `proposedLog` after it is sent. The payload is assigned a slot by checking which slots are not already used, by negating `proposedLog`, so adding back to `proposedLog` also requires another timestep.

**Comment by justinj** [comment]
That's super useful—I'm not sure if our current proposal of "state either gets drained or not drained" is rich enough to support all of these efficiently, but I can't think of a general mechanism that would, so I think for the meantime we should go ahead with "tag a piece of state as draining at end of tick or not," and then fall back to more expensive stuff for more complicated behaviours.

There's probably some interesting work in figuring out how to get "conditional persists" to work. You probably want a different structure if you expect most of the data to stick around each tick vs. most of the data draining each tick, but I wonder if there's a nice data structure that would encapsulate this. I'm not really sure!

**Comment by jhellerstein** [comment]
Update: in surface syntax we can now achieve persistence Dedalus-style by piping data through `next_epoch` but (a) it's inelegant (b) it's inefficient, (c) we're counting on the user to manage persistence semantics.

Maybe (c) is appropriate at this level of the stack, but it's pretty unclear why, for example, `join` persists across epochs and `reduce` does not. So we should think through the "baseline" persistence semantics for hydroflow ops. See discussion in [google doc](https://docs.google.com/document/d/1S-3MwTYOm-HfcqTRjlXXfsXoHHtSS0_oBjieASp2bbw/edit#heading=h.gq275euimk3)
