### ISSUE TITLE
Performance testing for mapping into/out of joins

### ISSUE THREAD

**Issue by jhellerstein** [hydro-project/hydroflow#185]
Is there an expense to the mapping once the compiler has done its magic, relative to tuples that "happen to be" set up right and don't need maps? Would a closure for "key access" on each input help the compiler more than mapping? And/or should we have some fast-path that makes the "relational joins on relational data" go fast?

**Comment by MingweiSamuel** [comment]
Ex:

Cost of putting things into tuples
Cost of selecting Nth value as the join key (rather than only the first)
New `join_by` operator?

**Comment by MingweiSamuel** [comment]
Can maybe tell just by the current flame graphs if this is causing any performance overhead? @zzlk

**Comment by zzlk** [comment]
I took a quick initial swing at this and from what I can tell, to my surprise, the behavior of the mapped versions do indeed perform _differently_. I was not expecting this. I was expecting the mapped ones, as long as the data is the same, to compile down to exactly the same code, so no difference should be detectable.

I ran the benchmarks with
```
sudo nice -n-20 taskset 0x4 sudo -u stan cargo bench -p benches -- mapjoinperf --output-format bencher --measurement-time 10
```

making sure to disable the intel turbo boost feature on my cpu otherwise it's hard to get sensible results:

```
echo "1" | sudo tee /sys/devices/system/cpu/intel_pstate/no_turbo
```

and I got these results:

![2023-03-15_23:30:18](https://user-images.githubusercontent.com/2418897/225533639-c8aeae1d-5020-4ef6-b4ae-8a5b4e9d8e0a.png)

**Comment by jhellerstein** [comment]
Hypothesis is that LTO makes this irrelevant; need to confirm.
