### ISSUE TITLE
WASM running of hydroflow

### ISSUE THREAD

**Issue by MingweiSamuel** [hydro-project/hydroflow#329]
Should be possible to do, but do we want to? Would be fun but maybe not high priority. Mentioned in slack briefly @shadaj

**Comment by shadaj** [comment]
I've been slowly working through this in down time, current goal is to get a demo on the website

**Comment by MingweiSamuel** [comment]
The surface syntax parsing and processing should be good, but I anticipate issues with Tokio on WASM

**Comment by shadaj** [comment]
Oh yes true, I guess there are two issues: get the Hydroflow Language / Dedalus compilers to work on WASM, and get the Hydroflow runtime to work. Found https://github.com/shosti/wraft as a potentially interesting benchmark for the runtime; in principle we should be able to wire up WebRTC as the networking layer with Tokio on WASM.

**Comment by MingweiSamuel** [comment]
#331 `hydroflow_lang`

**Comment by shadaj** [comment]
@tylerhou will look into this soon

**Comment by tylerhou** [comment]
I took a brief look at this today. The latest version of Tokio has limited support for WASM including runtime: https://github.com/tokio-rs/tokio/blob/a7945b469d634cf205094d8a1661720358622cc0/tokio/src/lib.rs#L387. Our current version also supports all those features above but it is not documented (tested by compiling for WASM with those features enabled).

For WASM we would need to not specify `tokio { ... features = "full" }` in [hydroflow/Cargo.toml](https://github.com/hydro-project/hydroflow/blob/main/hydroflow/Cargo.toml#L57) and instead selectively enable the features based if the target is WASM. hydroflow compiles if we do this and also disable diagnostics for hydroflow_lang. Very rough patch that compiles for WASM attached.

There are still two outstanding issues:

1. Documentation for tokio says that while `time` compiles for non-WASI WASM targets, it panics at runtime. We use timers in only one file -- hydroflow/tests/surface_async.rs -- and its a test, so maybe this is not an issue.
2. `cargo test -p hydroflow --target wasm32-unknown-unknown` does not work because the getrandom library (which is included tvia rand and transitively through textnonce -> rand in dev dependencies) requires us to build with the `js` feature flag or target wasm32-unknown-emscripten so it knows which random implementation to call. https://docs.rs/getrandom/latest/getrandom/#webassembly-support

[wasm.patch](https://github.com/hydro-project/hydroflow/files/10673525/wasm.patch)

**Comment by shadaj** [comment]
This is very exciting progress! For the second issue, I think we can add a `js` feature flag to hydroflow itself that then enables the `js` flag on `getrandom`. That way we can support both `wasm32-unknown-unknown` and `wasm32-wasi` (I'm not particularly concerned about `-emscripten`).

**Comment by MingweiSamuel** [comment]
(Compilation in WASM, i.e. running `hydroflow_lang/macro`, has been working for a long time)

**Comment by MingweiSamuel** [comment]
Works in general, networking (TCP analogous to websockets, other options as well), #1440 will be the main issue
