### ISSUE TITLE
Questions about *Invited Paper: Initial Steps Toward a Compiler for Distributed Programs*

### ISSUE THREAD

**Issue by segeljakt** [hydro-project/hydroflow#921]
Hi, I recently found out about Hydroflow and it looks very interesting. I finished reading the paper *Invited Paper: Initial Steps Toward a Compiler for Distributed Programs* and I am wondering about some details:

* If I understand correctly, the main point of making dataflow operators consume and produce lattices (bounded join semi-lattices with a top element) is that their behaviour becomes deterministic in the presence of batched, duplicated and/or out-of-order messages, as long as messages are eventually delivered. On the surface, it appears like Hydroflow uses UDP and not TCP. Therefore I am wondering, how does Hydroflow handle the risk of lost messages?
* There are some slight differences between the lattices defined in the paper and in the code. The BP lattice in the paper is represented as `(Vec<T>, usize)` and in the [code](https://github.com/hydro-project/hydroflow/blob/fc7d27d94b7dafb7b25f7df74004f6450b4854de/hydroflow/examples/shopping/lattices.rs#L135-L138) as roughly `(Vec<T>, Option<usize>)`. The SSIV lattice in the paper is represented as `(T, usize, Option<usize>)` and in the [code](https://github.com/hydro-project/hydroflow/blob/fc7d27d94b7dafb7b25f7df74004f6450b4854de/hydroflow/examples/shopping/lattices.rs#L14-L17) as roughly `(BTreeMap<usize, T>, Option<usize>)`. It seems to me that the BP definition in the code is superior to the paper's since the `len(S)` does not need to be known upfront. The SSIV definition in the paper seems superior to the code's since it's fixed size. Is there a definitive lattice representation one should go by when building applications like the shopping cart?
* Is it in general possible to represent lattices using a fixed amount of memory (e.g., like `(T, usize, Option<usize>)` in the paper), or do their size grow over time?

**Comment by MingweiSamuel** [comment]
Thanks for your interest!

* Yup. "Latticeflow" can be thought of as a generalization of dataflow-- dataflow is just latticeflow where the items are treated as set-union lattices. UDP is not a specific networking design choice, it is just easier to set up. We currently don't properly handle lost messages, but TCP-like ACK messages should be sufficient. However the statefulness and ordered messages of TCP is more than we need.
* I think we should think of both the paper and code version of BP lattices as having a length represented by `Option<usize>` (aka `WithBot<usize>`), as we can't really know beforehand how long it will eventually be. But note that this value can only be set once (or to one specific value) to be correct, so you have to be careful. For SSIV the representations should be thought of as equivalent, the paper describes it as a _set_ containing `(idx: usize, item: T, len: Option<usize>)` _items_, so you end up with `Set<(usize, T, Option<usize>)>` but with equality really only determined by the `idx: usize`. Because of that, and since the `len: Option<usize>` can only be one value anyway, `(BTreeMap<usize, T>, Option<usize>)` is a cleaner representation.
* So generally the lattices will always grow in size over time. But also, in "latticeflow," the individual lattice instances which flow through an edge should be thought of as together representing a larger lattice value. Although that larger lattice value is always growing in size, the individual lattice elements can each be a small "atomic" fixed size. Like individual rows in a larger relation. In the case of the paper SSIV example, the `(usize, T, Option<usize>)` items are the "rows" and we get the whole growing value when we materialize/merge them together (which we don't necessarily always need to do).

Let me know if that makes sense and feel free to ask more questions

**Comment by segeljakt** [comment]
Hi, I am sorry about the late response. Thank you for the great clarification. I have some more questions:

* Do operators in a latticeflow represent their state as lattices? I'm thinking that maybe when an operator receives an event it does a join operation with its lattice and forwards the result. 🤔
* Is there a reason for having `Option<usize>` instead of `bool` to indicate that the cart should be checked out? Maybe the `usize` is useful for asserting that the cart has the right size.

**Comment by MingweiSamuel** [comment]
* Not sure exactly what you mean, but yeah all operator state should be lattices as well ideally, for lattice flow
* Yeah `usize` does let us catch the logical error if there are multiple conflicting checkouts. Note that this means that in some sense it is not really a proper lattice-- you should always be able to merge any two instances in a proper lattice
